### ISSUE TITLE
Undefined variable $hours_left

### ISSUE THREAD

**Issue by addyh** [XjSv/Cooked#10]
A warning for 2 lines is given in PHP version 8.2 in some cases, (Cooked version  1.7.13 -- but it's evident the issue still exists on the current version of the plugin). in the case when $minutes is greater than or equal to 1440.

```
PHP Warning: Undefined variable $hours_left in /wp-content/plugins/cooked/includes/class.cooked-measurements.php on line 680

PHP Warning: Undefined variable $hours_left in /wp-content/plugins/cooked/includes/class.cooked-measurements.php on line 683
```

Line  680 was:
```php
				return 'P'.intval( $days ).'DT'.( $hours_left ? intval( $hours_left ) : 0 ).'H'.( $minutes_left ? intval( $minutes_left ) : 0 ).'M';
```

And line 683 was:

```php
				echo ( $hours_left ? '&nbsp;' . self::singular_plural( sprintf( esc_html__( '%d hr','cooked' ), number_format_i18n($hours_left) ), sprintf( esc_html__( '%d hrs','cooked' ), number_format_i18n($hours_left) ), $hours_left ) : '' );

```

This could be fixed by wrapping the offending $hours_left with an isset($hours_left) && $hours_left, but I opted to just set $hours_left = 0 in the line above. 

I will submit a PR shortly, which will be based off of the 'develop' branch.

**Comment by XjSv** [comment]
Thanks for the contribution, I merged the PR.
